//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.OrdersBooks = new HashSet<OrdersBooks>();
            this.AppUsers = new HashSet<AppUser>();
        }
    
        public int BookId { get; set; }
        public string Title { get; set; }
        public string ISBN { get; set; }
        public short Year { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
        public byte[] Image { get; set; }
        public int Price { get; set; }
        public int Position { get; set; }
        public int Qty { get; set; }
        public bool Featured { get; set; }
        public string AuthorName { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersBooks> OrdersBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppUser> AppUsers { get; set; }
    }
}
