//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookOrder()
        {
            this.OrdersBooks = new HashSet<OrdersBooks>();
        }
    
        public int OrderId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<int> CouponId { get; set; }
        public int UserId { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Coupon Coupon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersBooks> OrdersBooks { get; set; }
    }
}
