//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersBooks
    {
        public int OrderId { get; set; }
        public int BookId { get; set; }
        public int Qty { get; set; }
        public int ItemPrice { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual BookOrder BookOrder { get; set; }
    }
}
